### ISSUE TITLE
Problem with Laravel 5.2 Service Provider

### ISSUE THREAD

**Issue by suth** [MattKetmo/EmailChecker#26]
I see that @olsgreen has written the Laravel service provider, so this might be something he can help debug. I'm using Laravel 5.2 and I've followed the docs on Laravel usage but get an error that "validateNotThrowAway" is not a valid method when using the "not_throw_away" validation rule. Could something have changed in Laravel since the service provider was written?

Managed to manually implement the functionality pretty easily, and if I find time I'll take a look to see if I can figure out what's going on.

**Comment by olsgreen** [comment]
@suth It could quite possibly be a minor change in architecture, I think I originally tested with 5.0. It should be a trivial fix, I'll take a look when I can. Thanks for reporting.

**Comment by olsgreen** [comment]
@suth I've tested with 5.2.32 following the instructions & code samples without a problem. You may have missed a step? Which version of PHP are you using?

**Comment by suth** [comment]
It's a Homestead box with PHP 7. Just tested on a clean install of 5.2.31 and had the same issue until I changed `protected $defer = true;` to false. Looked it up and the docs say to only use defer if the provider is only registering bindings in the service container.

If I add `$checker = app()->make('email.checker');` somewhere before using the `not_throw_away` validation rule, the boot method on the provider gets called and the validator rule is properly registered.

**Comment by olsgreen** [comment]
@suth An oversight on my behalf, thanks! @MattKetmo Can you merge and close, cheers.
