### ISSUE TITLE
Add new domain name

### ISSUE THREAD

**Issue by mikaelcom** [MattKetmo/EmailChecker#29]
Hi,

First, thanks for your project, it saved me time!

It seems *@lackmail.ru is a temporary email domain from https://temp-mail.org/ that does not exist in your settings, could you add it ?

Complete list is on the https://temp-mail.org/en/option/change page

Thanks,

**Comment by mikaelcom** [comment]
Could you add @mvrht.com from https://10minutemail.com :)

**Comment by whitnelson** [comment]
Also mvrht.net
