### ISSUE TITLE
Detect alias

### ISSUE THREAD

**Issue by qneyrat** [MattKetmo/EmailChecker#40]
Ideas to detect if address is an alias like example+1@gmail.com or for example [yahoo](https://help.yahoo.com/kb/SLN16026.html) ?

**Comment by MattKetmo** [comment]
Aliases are valid emails, it's a standard most of email providers apply. Why do you want to detect them?

**Comment by qneyrat** [comment]
User can signup my app with alias address and spam my service.

**Comment by MattKetmo** [comment]
If you buy any domain name you can also have an infinite amount of valid email addresses, without using any alias.

In general it's considered bad practice to forbid aliases. I'm using them heavily in many services even if I need create only one account.

So I'm 👎 to implement it in this lib.

**Comment by qneyrat** [comment]
okay, I agree 👍 .
