### ISSUE TITLE
List of domains and licensing

### ISSUE THREAD

**Issue by salaros** [MattKetmo/EmailChecker#61]
Recently I've created a library (actually libraries for [.NET](https://github.com/salaros/is-biz-mail-dotnet), [PHP](https://github.com/salaros/is-biz-mail-php) and [JavaScript](https://github.com/salaros/is-biz-mail-js)) for detecting business email addresses by comparing them to the list of known free email providers, such as Gmail, Yahoo etc

Unfortunately I cannot depend on your library, because I have JavaScript, .NET and soon will also feature Java, Python etc implementations. So I would like to use the [list of domains](https://raw.githubusercontent.com/MattKetmo/EmailChecker/master/res/throwaway_domains.txt) you have collected during last 5-6 years, but I want to credit you properly.

I was going to append you license to my LICENSE file as well as mentioning you in credits section of the README file.

Is it OK for you?

**Comment by MattKetmo** [comment]
Hello, sorry for late answer. I'm totally fine if you copy the list of domains. 
I even don't care about credit since I don't consider being owner of those. It has been taken from various places and people, and I didn't track the original sources. So feel free to do whatever you want ;)

**Comment by salaros** [comment]
Actually I've already included it into my build system and credited you 😄

![image](https://user-images.githubusercontent.com/675348/53579542-cbaaba00-3b8a-11e9-8dcc-ebfd91e32694.png)
